spring:
  datasource:
    url: jdbc:mysql://13.125.249.178:3306/test
    username: kihwan
    password: 48564856 #docker mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:tcp://localhost/~/runningDB
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug
  #   org.hibernate.type: trace