# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ myworkflow ]
  pull_request:
    branches: [ myworkflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Docker build
      run: | 
       docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
       docker build -t running-web .
       docker tag running-web sekihwan/running-web:${GITHUB_SHA::7}
       docker push sekihwan/running-web:${GITHUB_SHA::7}
    
    - name: Deploy 
      uses: actions/checkout@v2
      with: 
        host: ec2-3-34-178-11.ap-northeast-2.compute.amazonaws.com 
        username: ec2-user 
        key: ${{ secrets.PRIVATE_KEY }} 
        envs: GITHUB_SHA 
        script: | 
          docker pull sekihwan/running-web:${GITHUB_SHA::7} 
          docker tag sekihwan/running-web:${GITHUB_SHA::7} mate 
          docker stop mate 
          docker run -d --rm --name mate -p 8080:8080 mate
